"""empty message

Revision ID: 20cc536bdc4e
Revises: 
Create Date: 2020-09-07 14:03:26.467937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cc536bdc4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kat', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('pas', sa.String(length=20), nullable=True),
    sa.Column('gambar', sa.Text(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tilte', sa.Text(), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('data_time', sa.DateTime(), nullable=False),
    sa.Column('userku_id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['userku_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conten')
    op.drop_table('user')
    op.drop_table('rol')
    op.drop_table('kategori')
    # ### end Alembic commands ###
